[package]
name = "mediadepot"
version = "1.0.0"
authors = ["Charles Tabor <chastabor@gmail.com>"]

[dependencies]
futures = "^0.1.16"
hyper = "^0.11"
tokio-core = "^0.1"
tokio-proto = "^0.1.1"
# Use rustls for front end to stick with rust protected ssl
hyper-rustls = "0.11.0"
# use openssl for backend CAS requests as it doesn't implement forward secrecy
hyper-openssl = "0.3.0"
url = "^0.2"
xml-rs = "^0.7"
percent-encoding = "1.0.0"
base64 = "0.6.0"
lazy_static = "0.2.9"
mime = "0.3.5"
mime_guess = "1.8.2"
serde = "^1.0.21"
serde_json = "^1.0.6"
serde_derive = "^1.0.21"
chrono = "^0.4"
time = "0.1"
tera = "^0.10.10"
error-chain = "0.10"
#rayon-core = "1.3.0"
# keep the following in sync with rustls
jsonwebtoken = "4.0.0"
ring  = "0.12.1"
rustls = "0.11.0"
tokio-rustls = "0.4.0"
